# Site settings
title:
email: contact@cling.online
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cling.online" # the base hostname & protocol for your site

twitter_username: clingonline
github_username: clingonline

# Build settings
markdown: kramdown
